repos:
  - repo: local
    hooks:
      - id: lint-check
        name: lint (check only)
        entry: ./lint.sh --check
        language: system
        pass_filenames: false
        always_run: true
